### ISSUE TITLE
HAR files contain \v as escape for U+000B LINE TABULATION

### ISSUE THREAD

**Issue by foolip** [HTTPArchive/legacy.httparchive.org#142]
Many HAR files contains `\v` escapes, which Python's `json.decode` throws an exception for.

See https://www.json.org/ or section 9 "Strings" in http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

An example of such a file is gs://httparchive/chrome-Dec_15_2017/171215_4J_8YPB.har.gz, which has `\v` at byte offset 803179, shortly after the string `"mimeType":"text/plain","text":"wOF2`...

**Comment by foolip** [comment]
FWIW, looks like `JSON.parse` in JavaScript also doesn't support `\v`. What JSON decoder would one need to use for this?

**Comment by foolip** [comment]
171215_1H_30Q5.har.gz also has a `\O` and as I'm trying to work around problems there seems like there's no end to it. @pmeenan, do you know what's going on here?

**Comment by rviscomi** [comment]
After much fumbling over the assignments, sending this over to Pat to investigate.

**Comment by pmeenan** [comment]
I'll take a look and see if I can get to the underlying issue.  Probably something screwy with PHP's json encoding (which barely supports UTF-8 if I remember correctly).  Not sure why it would be new though.

**Comment by pmeenan** [comment]
Looks like it is picking up woff2 fonts that have a content type of text/plain and including the bodies.  Specifically request #39 [here](http://httparchive.webpagetest.org/result/171215_4J_8YPB/2/details/#waterfall_view_step1).

Additionally complicated by the PHP code that generated the JSON detecting the content as UTF-8 instead of binary data and PHP's json_encode happily including the binary data as if it was a string.

I have a server-side mitigation [in place now](https://github.com/WPO-Foundation/webpagetest/commit/93b968fe08168b1c196f56eafce596d4723ecb5b#diff-ab9e5a1ea43ed7b3da36904faa285b03R339) where it runs the encoding detection in strict mode (scans the full string) and skips bodies for anything that isn't a text encoding.  [Downloading the HAR](http://httparchive.webpagetest.org/export.php?test=171215_4J_8YPB&run=2&cached=0&bodies=1&pretty=1) from the server shows the fix is working but it won't help with existing crawls.

I'm looking at an agent-side fix as well so the binary files aren't stored in the first place.

After I finish up with the agent-side fix I'll see about creating a script that can go through the existing HAR's on the server, strip out any invalid bodies and push the result back into the bucket (will take a while to run given the terabytes of HAR data - I'll start with the 12/15 crawl if it will help.

I'll update here as I make more progress.

**Comment by pmeenan** [comment]
Agent-side fix is [also in place now](https://github.com/WPO-Foundation/wptagent/commit/bbc0577dd213384b9e6ed41cb8af1f9028c9b2a6).  Looking into cleaning up the data now.

**Comment by pmeenan** [comment]
First pass of cleanup on the Dec 15th desktop crawl is going now.  It looks like it fixes about 80% of the files that don't parse as json (deletes any body that is a non-parseable json string).  It's running fairly slowly though and will take ~6 days to complete.

Tomorrow I'll look at some of the cases it couldn't fix to see if there is something common going on with those and also switch it to download the har files in batches instead of one at a time which should speed it up significantly.

**Comment by foolip** [comment]
Wow, thanks for the quick action on this @pmeenan! I will be quite fine just waiting for a new crawl and am not blocked on being able to process the Dec 15th crawl, but fixing it makes sense.

Will binary files be excludes unconditionally? I guess that'll make the size of the data a lot smaller, but what if we want to do some analysis of what WOFF2 files in the wild look like?

**Comment by pmeenan** [comment]
Binary files are always excluded unconditionally from WPT's saving of response bodies.  It would be possible to store them as base-64 encoded strings which the HAR spec supports but it's not something WPT has ever done (largely because of file size issues).

**Comment by pmeenan** [comment]
Not sure yet on how they got there but the remaining failures had control characters in the strings of actual text files (css, etc) but it wasn't being filtered out by the earlier logic.  The cleaning logic was updated and is running against the HARs now.  Checking a few of the pages that showed the issue to make sure that the agent and server changes are successfully filtering them out (or escaping) and they won't be a problem going forward.

**Comment by rviscomi** [comment]
To confirm, has this been fixed?

**Comment by pmeenan** [comment]
It should be but it would be nice to verify.  I have several layers of filtering in place to try to make sure none get through but I can't guarantee it got them all.  The common problem of fonts getting included as text resources should be fixed.
